[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remapings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/"]
# remapings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']
ffi = true 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
